# Generated by Django 4.1.2 on 2022-11-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(upload_to='BlogImg', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='creat_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
