# Generated by Django 4.1.2 on 2022-11-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_blog_blog_img_alter_blog_creat_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(upload_to='media/BlogImg', verbose_name='Image'),
        ),
    ]
